In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("raw_datasets/chembl/chembl_mlm_intrinsic.csv")

In [3]:
df

,activity_id,molecule_chembl_id,smiles,structure_status,target_chembl_id,target_name,assay_chembl_id,document_chembl_id,data_year,standard_type,standard_relation,standard_value,standard_units,data_validity_comment,activity_comment,assay_type,assay_description,classification_text,classification_bucket
0,2258431,CHEMBL524645,CC(C)Oc1ccc(S(C)(=O)=O)cc1C(=O)N1CCN(c2ccc(C(F...,smiles_found,CHEMBL612558,ADMET,CHEMBL1007123,CHEMBL1141693,2008.0,CL,=,0.0,mL.min-1.g-1,NaN,NaN,A,Metabolic stability in mouse liver microsomes ...,metabolic stability in mouse liver microsomes ...,chembl_mlm_intrinsic
1,2258432,CHEMBL521899,CS(=O)(=O)c1ccc(OCC2CC2)c(C(=O)N2CCN(c3ccc(C(F...,smiles_found,CHEMBL612558,ADMET,CHEMBL1007123,CHEMBL1141693,2008.0,CL,=,1000.0,mL.min-1.g-1,NaN,NaN,A,Metabolic stability in mouse liver microsomes ...,metabolic stability in mouse liver microsomes ...,chembl_mlm_intrinsic
2,2258433,CHEMBL496749,CS(=O)(=O)c1ccc(-c2ccc(F)cc2)c(C(=O)N2CCN(c3cc...,smiles_found,CHEMBL612558,ADMET,CHEMBL1007123,CHEMBL1141693,2008.0,CL,=,5000.0,mL.min-1.g-1,NaN,NaN,A,Metabolic stability in mouse liver microsomes ...,metabolic stability in mouse liver microsomes ...,chembl_mlm_intrinsic
3,2258434,CHEMBL496540,CS(=O)(=O)c1ccc(-c2ccccc2)c(C(=O)N2CCN(c3ccc(C...,smiles_found,CHEMBL612558,ADMET,CHEMBL1007123,CHEMBL1141693,2008.0,CL,=,9000.0,mL.min-1.g-1,NaN,NaN,A,Metabolic stability in mouse liver microsomes ...,metabolic stability in mouse liver microsomes ...,chembl_mlm_intrinsic
4,2258435,CHEMBL497999,CS(=O)(=O)c1ccc(OCC2CC2)c(C(=O)N2CCN(c3ccc(C#N...,smiles_found,CHEMBL612558,ADMET,CHEMBL1007123,CHEMBL1141693,2008.0,CL,=,9000.0,mL.min-1.g-1,NaN,NaN,A,Metabolic stability in mouse liver microsomes ...,metabolic stability in mouse liver microsomes ...,chembl_mlm_intrinsic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4892,2566704,CHEMBL469231,Cn1cc(S(C)(=O)=O)cc1-c1c2c(=O)n(C)c(=O)n(CC3CC...,smiles_found,CHEMBL612558,ADMET,CHEMBL967971,CHEMBL1155910,2008.0,CL,=,64.0,mL.min-1.g-1,NaN,NaN,A,Intrinsic clearance in mouse liver microsome,intrinsic clearance in mouse liver microsome |...,chembl_mlm_intrinsic
4893,2566709,CHEMBL467148,Cn1cc(S(C)(=O)=O)nc1-c1c2c(=O)n(C)c(=O)n(CC3CC...,smiles_found,CHEMBL612558,ADMET,CHEMBL967971,CHEMBL1155910,2008.0,CL,=,56.0,mL.min-1.g-1,NaN,NaN,A,Intrinsic clearance in mouse liver microsome,intrinsic clearance in mouse liver microsome |...,chembl_mlm_intrinsic
4894,2566717,CHEMBL469008,Cc1oc(S(C)(=O)=O)cc1-c1c2c(=O)n(C)c(=O)n(CC3CC...,smiles_found,CHEMBL612558,ADMET,CHEMBL967971,CHEMBL1155910,2008.0,CL,=,61.0,mL.min-1.g-1,NaN,NaN,A,Intrinsic clearance in mouse liver microsome,intrinsic clearance in mouse liver microsome |...,chembl_mlm_intrinsic
4895,2566718,CHEMBL469007,Cn1c(=O)c2c(-c3oc(S(C)(=O)=O)cc3Cl)n(Cc3ccnc4c...,smiles_found,CHEMBL612558,ADMET,CHEMBL967971,CHEMBL1155910,2008.0,CL,=,22.0,mL.min-1.g-1,NaN,NaN,A,Intrinsic clearance in mouse liver microsome,intrinsic clearance in mouse liver microsome |...,chembl_mlm_intrinsic
4896,2566719,CHEMBL513533,Cn1c(=O)c2c(-c3ccc(S(C)(=O)=O)o3)n(Cc3ccnc4ccc...,smiles_found,CHEMBL612558,ADMET,CHEMBL967971,CHEMBL1155910,2008.0,CL,=,14.0,mL.min-1.g-1,NaN,NaN,A,Intrinsic clearance in mouse liver microsome,intrinsic clearance in mouse liver microsome |...,chembl_mlm_intrinsic

#### Certain assays mention values outside of typical range showing very high HLM CLint values. For this dataset I remove them. Depending on the procedure they can also be kept, if the reason that they are outside of typical range is related to the compounds themselves and not errors from the experimental or procedual side of things

In [4]:
df["data_validity_comment"].unique()

array([nan, 'Outside typical range'], dtype=object)

In [5]:
df_inside_range = df[df["data_validity_comment"].isna()]

In [6]:
df_inside_range

,activity_id,molecule_chembl_id,smiles,structure_status,target_chembl_id,target_name,assay_chembl_id,document_chembl_id,data_year,standard_type,standard_relation,standard_value,standard_units,data_validity_comment,activity_comment,assay_type,assay_description,classification_text,classification_bucket
0,2258431,CHEMBL524645,CC(C)Oc1ccc(S(C)(=O)=O)cc1C(=O)N1CCN(c2ccc(C(F...,smiles_found,CHEMBL612558,ADMET,CHEMBL1007123,CHEMBL1141693,2008.0,CL,=,0.0,mL.min-1.g-1,NaN,NaN,A,Metabolic stability in mouse liver microsomes ...,metabolic stability in mouse liver microsomes ...,chembl_mlm_intrinsic
1,2258432,CHEMBL521899,CS(=O)(=O)c1ccc(OCC2CC2)c(C(=O)N2CCN(c3ccc(C(F...,smiles_found,CHEMBL612558,ADMET,CHEMBL1007123,CHEMBL1141693,2008.0,CL,=,1000.0,mL.min-1.g-1,NaN,NaN,A,Metabolic stability in mouse liver microsomes ...,metabolic stability in mouse liver microsomes ...,chembl_mlm_intrinsic
2,2258433,CHEMBL496749,CS(=O)(=O)c1ccc(-c2ccc(F)cc2)c(C(=O)N2CCN(c3cc...,smiles_found,CHEMBL612558,ADMET,CHEMBL1007123,CHEMBL1141693,2008.0,CL,=,5000.0,mL.min-1.g-1,NaN,NaN,A,Metabolic stability in mouse liver microsomes ...,metabolic stability in mouse liver microsomes ...,chembl_mlm_intrinsic
3,2258434,CHEMBL496540,CS(=O)(=O)c1ccc(-c2ccccc2)c(C(=O)N2CCN(c3ccc(C...,smiles_found,CHEMBL612558,ADMET,CHEMBL1007123,CHEMBL1141693,2008.0,CL,=,9000.0,mL.min-1.g-1,NaN,NaN,A,Metabolic stability in mouse liver microsomes ...,metabolic stability in mouse liver microsomes ...,chembl_mlm_intrinsic
4,2258435,CHEMBL497999,CS(=O)(=O)c1ccc(OCC2CC2)c(C(=O)N2CCN(c3ccc(C#N...,smiles_found,CHEMBL612558,ADMET,CHEMBL1007123,CHEMBL1141693,2008.0,CL,=,9000.0,mL.min-1.g-1,NaN,NaN,A,Metabolic stability in mouse liver microsomes ...,metabolic stability in mouse liver microsomes ...,chembl_mlm_intrinsic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4892,2566704,CHEMBL469231,Cn1cc(S(C)(=O)=O)cc1-c1c2c(=O)n(C)c(=O)n(CC3CC...,smiles_found,CHEMBL612558,ADMET,CHEMBL967971,CHEMBL1155910,2008.0,CL,=,64.0,mL.min-1.g-1,NaN,NaN,A,Intrinsic clearance in mouse liver microsome,intrinsic clearance in mouse liver microsome |...,chembl_mlm_intrinsic
4893,2566709,CHEMBL467148,Cn1cc(S(C)(=O)=O)nc1-c1c2c(=O)n(C)c(=O)n(CC3CC...,smiles_found,CHEMBL612558,ADMET,CHEMBL967971,CHEMBL1155910,2008.0,CL,=,56.0,mL.min-1.g-1,NaN,NaN,A,Intrinsic clearance in mouse liver microsome,intrinsic clearance in mouse liver microsome |...,chembl_mlm_intrinsic
4894,2566717,CHEMBL469008,Cc1oc(S(C)(=O)=O)cc1-c1c2c(=O)n(C)c(=O)n(CC3CC...,smiles_found,CHEMBL612558,ADMET,CHEMBL967971,CHEMBL1155910,2008.0,CL,=,61.0,mL.min-1.g-1,NaN,NaN,A,Intrinsic clearance in mouse liver microsome,intrinsic clearance in mouse liver microsome |...,chembl_mlm_intrinsic
4895,2566718,CHEMBL469007,Cn1c(=O)c2c(-c3oc(S(C)(=O)=O)cc3Cl)n(Cc3ccnc4c...,smiles_found,CHEMBL612558,ADMET,CHEMBL967971,CHEMBL1155910,2008.0,CL,=,22.0,mL.min-1.g-1,NaN,NaN,A,Intrinsic clearance in mouse liver microsome,intrinsic clearance in mouse liver microsome |...,chembl_mlm_intrinsic
4896,2566719,CHEMBL513533,Cn1c(=O)c2c(-c3ccc(S(C)(=O)=O)o3)n(Cc3ccnc4ccc...,smiles_found,CHEMBL612558,ADMET,CHEMBL967971,CHEMBL1155910,2008.0,CL,=,14.0,mL.min-1.g-1,NaN,NaN,A,Intrinsic clearance in mouse liver microsome,intrinsic clearance in mouse liver microsome |...,chembl_mlm_intrinsic

The ChEMBL retrieved data contains values with various units. While we retain the applicable mL.min-1.kg-1 and mL.min-1.g-1 which we need to scale we drop the remainder, including ml/min.mg due to it only having 5 data points and min.kg/L having 4 data points due to them requiring a separate scaling algorithm most likely

In [7]:
df_inside_range["standard_units"].unique()

array(['mL.min-1.g-1', 'mL.min-1.kg-1', 'ug/min', 'uL/ml', '%',
       'uL/ml/kg'], dtype=object)

In [8]:
df_inside_range["standard_units"].value_counts().reindex([
    'mL.min-1.kg-1', 'mL.min-1.g-1', 'nmol/mg/min', 'nM/min/mg',
    'ml/min.mg', 'mg/ml/g', 'min.kg/L', 'hr.Kg/L', 'uL/ml/kg',
    'uL/ml.millig', 'ug ml-1', 'ug/min/mg', 'uL/min', 'ug/min',
    'L/min'
], fill_value=0)

standard_units
mL.min-1.kg-1    1213
mL.min-1.g-1     3500
nmol/mg/min         0
nM/min/mg           0
ml/min.mg           0
mg/ml/g             0
min.kg/L            0
hr.Kg/L             0
uL/ml/kg           15
uL/ml.millig        0
ug ml-1             0
ug/min/mg           0
uL/min              0
ug/min              7
L/min               0
Name: count, dtype: int64

In [9]:
df_inside_range = df_inside_range[
    df_inside_range["standard_units"].isin([
        "mL.min-1.kg-1",
        "mL.min-1.g-1",
    ])
].reset_index(drop=True)

In [10]:
df_inside_range

,activity_id,molecule_chembl_id,smiles,structure_status,target_chembl_id,target_name,assay_chembl_id,document_chembl_id,data_year,standard_type,standard_relation,standard_value,standard_units,data_validity_comment,activity_comment,assay_type,assay_description,classification_text,classification_bucket
0,2258431,CHEMBL524645,CC(C)Oc1ccc(S(C)(=O)=O)cc1C(=O)N1CCN(c2ccc(C(F...,smiles_found,CHEMBL612558,ADMET,CHEMBL1007123,CHEMBL1141693,2008.0,CL,=,0.0,mL.min-1.g-1,NaN,NaN,A,Metabolic stability in mouse liver microsomes ...,metabolic stability in mouse liver microsomes ...,chembl_mlm_intrinsic
1,2258432,CHEMBL521899,CS(=O)(=O)c1ccc(OCC2CC2)c(C(=O)N2CCN(c3ccc(C(F...,smiles_found,CHEMBL612558,ADMET,CHEMBL1007123,CHEMBL1141693,2008.0,CL,=,1000.0,mL.min-1.g-1,NaN,NaN,A,Metabolic stability in mouse liver microsomes ...,metabolic stability in mouse liver microsomes ...,chembl_mlm_intrinsic
2,2258433,CHEMBL496749,CS(=O)(=O)c1ccc(-c2ccc(F)cc2)c(C(=O)N2CCN(c3cc...,smiles_found,CHEMBL612558,ADMET,CHEMBL1007123,CHEMBL1141693,2008.0,CL,=,5000.0,mL.min-1.g-1,NaN,NaN,A,Metabolic stability in mouse liver microsomes ...,metabolic stability in mouse liver microsomes ...,chembl_mlm_intrinsic
3,2258434,CHEMBL496540,CS(=O)(=O)c1ccc(-c2ccccc2)c(C(=O)N2CCN(c3ccc(C...,smiles_found,CHEMBL612558,ADMET,CHEMBL1007123,CHEMBL1141693,2008.0,CL,=,9000.0,mL.min-1.g-1,NaN,NaN,A,Metabolic stability in mouse liver microsomes ...,metabolic stability in mouse liver microsomes ...,chembl_mlm_intrinsic
4,2258435,CHEMBL497999,CS(=O)(=O)c1ccc(OCC2CC2)c(C(=O)N2CCN(c3ccc(C#N...,smiles_found,CHEMBL612558,ADMET,CHEMBL1007123,CHEMBL1141693,2008.0,CL,=,9000.0,mL.min-1.g-1,NaN,NaN,A,Metabolic stability in mouse liver microsomes ...,metabolic stability in mouse liver microsomes ...,chembl_mlm_intrinsic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4708,2566704,CHEMBL469231,Cn1cc(S(C)(=O)=O)cc1-c1c2c(=O)n(C)c(=O)n(CC3CC...,smiles_found,CHEMBL612558,ADMET,CHEMBL967971,CHEMBL1155910,2008.0,CL,=,64.0,mL.min-1.g-1,NaN,NaN,A,Intrinsic clearance in mouse liver microsome,intrinsic clearance in mouse liver microsome |...,chembl_mlm_intrinsic
4709,2566709,CHEMBL467148,Cn1cc(S(C)(=O)=O)nc1-c1c2c(=O)n(C)c(=O)n(CC3CC...,smiles_found,CHEMBL612558,ADMET,CHEMBL967971,CHEMBL1155910,2008.0,CL,=,56.0,mL.min-1.g-1,NaN,NaN,A,Intrinsic clearance in mouse liver microsome,intrinsic clearance in mouse liver microsome |...,chembl_mlm_intrinsic
4710,2566717,CHEMBL469008,Cc1oc(S(C)(=O)=O)cc1-c1c2c(=O)n(C)c(=O)n(CC3CC...,smiles_found,CHEMBL612558,ADMET,CHEMBL967971,CHEMBL1155910,2008.0,CL,=,61.0,mL.min-1.g-1,NaN,NaN,A,Intrinsic clearance in mouse liver microsome,intrinsic clearance in mouse liver microsome |...,chembl_mlm_intrinsic
4711,2566718,CHEMBL469007,Cn1c(=O)c2c(-c3oc(S(C)(=O)=O)cc3Cl)n(Cc3ccnc4c...,smiles_found,CHEMBL612558,ADMET,CHEMBL967971,CHEMBL1155910,2008.0,CL,=,22.0,mL.min-1.g-1,NaN,NaN,A,Intrinsic clearance in mouse liver microsome,intrinsic clearance in mouse liver microsome |...,chembl_mlm_intrinsic
4712,2566719,CHEMBL513533,Cn1c(=O)c2c(-c3ccc(S(C)(=O)=O)o3)n(Cc3ccnc4ccc...,smiles_found,CHEMBL612558,ADMET,CHEMBL967971,CHEMBL1155910,2008.0,CL,=,14.0,mL.min-1.g-1,NaN,NaN,A,Intrinsic clearance in mouse liver microsome,intrinsic clearance in mouse liver microsome |...,chembl_mlm_intrinsic

We also need to drop the 0 value data points due to them influencing log10 and with the OpenADMET not having 0 cases

In [11]:
# Keep only rows where smiles appears more than once
dups = df_inside_range[df_inside_range["smiles"].notna() & df_inside_range["smiles"].duplicated(keep=False)].copy()

# Sort so duplicate smiles are adjacent
dups = dups.sort_values(
    by=["smiles", "molecule_chembl_id", "activity_id"],
    kind="stable"
).reset_index(drop=True)

print(f"Duplicate rows: {len(dups)}")
print(f"Unique duplicated SMILES: {dups['smiles'].nunique()}")
print(dups[["smiles", "molecule_chembl_id", "activity_id"]].head(20))

Duplicate rows: 544
Unique duplicated SMILES: 216
                                               smiles molecule_chembl_id  \
0   C=CC(=O)N1CC2(CCN(c3nc(OC4CCN(C)CC4)nc4c(OCC)c...      CHEMBL5555430
1   C=CC(=O)N1CC2(CCN(c3nc(OC4CCN(C)CC4)nc4c(OCC)c...      CHEMBL5555430
2   C=CC(=O)Nc1cc(Nc2nccc(-c3cn(C)c4ccccc34)n2)c(O...      CHEMBL3353410
3   C=CC(=O)Nc1cc(Nc2nccc(-c3cn(C)c4ccccc34)n2)c(O...      CHEMBL3353410
4   CC(=O)N[C@H]1Cc2cccc(c2)Oc2cccc(c2)C[C@@H](C(=...      CHEMBL5180427
5   CC(=O)N[C@H]1Cc2cccc(c2)Oc2cccc(c2)C[C@@H](C(=...      CHEMBL5180427
6   CC(=O)Nc1ncc(CN2CCC3(CCN(c4cc(C)nc5ccccc45)C3)...      CHEMBL4741417
7   CC(=O)Nc1ncc(CN2CCC3(CCN(c4cc(C)nc5ccccc45)C3)...      CHEMBL4741417
8               CC(C)(C)OC(=O)N1CCCC(c2cn3cccnc3n2)C1      CHEMBL4577847
9               CC(C)(C)OC(=O)N1CCCC(c2cn3cccnc3n2)C1      CHEMBL4577847
10  CC(C)(C)[C@@H](Nc1ncnc2[nH]c(-c3cnn(CC(N)=O)c3...      CHEMBL5441539
11  CC(C)(C)[C@@H](Nc1ncnc2[nH]c(-c3cnn(CC(N)=O)c3...      CHEMBL5441539
12  CC(C)(C)[C@@H](Nc1ncnc2[nH]c(-c3cnn(CC(N)=O)c3...      CHEMBL5441427
13  CC(C)(C)[C@@H](Nc1ncnc2[nH]c(-c3cnn(CC(N)=O)c3...      CHEMBL5441427
14  CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1C[C@H]2[C@...      CHEMBL4802135
15  CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1C[C@H]2[C@...      CHEMBL4802135
16   CC(C)(C)c1cc(C(=O)N2CCCC(c3cc4ncccc4[nH]3)C2)on1      CHEMBL4460126
17   CC(C)(C)c1cc(C(=O)N2CCCC(c3cc4ncccc4[nH]3)C2)on1      CHEMBL4460126
18            CC(C)(C)c1ccc(-c2nc(CNC3CCCCCC3)co2)cc1      CHEMBL1857856
19            CC(C)(C)c1ccc(-c2nc(CNC3CCCCCC3)co2)cc1      CHEMBL1857856

    activity_id
0      25905393
1      25905395
2      18190079
3      18248519
4      24855389
5      25450258
6      22436050
7      22436055
8      19002766
9      19002767
10     25739876
11     25740408
12     25739948
13     25740152
14     25096907
15     25458741
16     19001741
17     19001742
18      6421009
19      6421012

In [12]:
dups_info = dups[["molecule_chembl_id", "smiles", "standard_value", "standard_units"]]

In [13]:
dups_info.tail(50)

,molecule_chembl_id,smiles,standard_value,standard_units
494,CHEMBL4520320,O=C(c1ccc(F)cc1)N1CCCC(c2cc3ncc(Cl)cc3[nH]2)C1,235.42,mL.min-1.g-1
495,CHEMBL4520320,O=C(c1ccc(F)cc1)N1CCCC(c2cc3ncc(Cl)cc3[nH]2)C1,969.83,mL.min-1.kg-1
496,CHEMBL4473162,O=C(c1ccc(F)cc1)N1CCCC(c2cc3ncccc3[nH]2)C1,337.21,mL.min-1.g-1
497,CHEMBL4473162,O=C(c1ccc(F)cc1)N1CCCC(c2cc3ncccc3[nH]2)C1,1076.67,mL.min-1.kg-1
498,CHEMBL4446610,O=C(c1cccc(C(F)(F)F)n1)N1CCCC(c2cc3ncccc3[nH]2)C1,64.03,mL.min-1.g-1
499,CHEMBL4446610,O=C(c1cccc(C(F)(F)F)n1)N1CCCC(c2cc3ncccc3[nH]2)C1,315.00,mL.min-1.kg-1
500,CHEMBL4442572,O=C(c1ccccc1)N1CC=C(c2cc3ncccc3[nH]2)CC1,305.00,mL.min-1.g-1
501,CHEMBL4442572,O=C(c1ccccc1)N1CC=C(c2cc3ncccc3[nH]2)CC1,1308.67,mL.min-1.kg-1
502,CHEMBL4578554,O=C(c1ccccc1)N1CCC(O)(c2cc3ncccc3[nH]2)CC1,192.98,mL.min-1.g-1
503,CHEMBL4578554,O=C(c1ccccc1)N1CCC(O)(c2cc3ncccc3[nH]2)CC1,956.00,mL.min-1.kg-1
504,CHEMBL4460602,O=C(c1ccccc1)N1CCC(c2cc3ncccc3[nH]2)CC1,1044.00,mL.min-1.g-1
505,CHEMBL4460602,O=C(c1ccccc1)N1CCC(c2cc3ncccc3[nH]2)CC1,4516.67,mL.min-1.kg-1
506,CHEMBL4446224,O=C(c1ccccc1)N1CCCC(c2cc3ncccc3[nH]2)C1,507.91,mL.min-1.g-1
507,CHEMBL4446224,O=C(c1ccccc1)N1CCCC(c2cc3ncccc3[nH]2)C1,2364.00,mL.min-1.kg-1
508,CHEMBL4546859,O=C(c1ccccc1)N1CCCC(c2cn3cccnc3n2)C1,127.37,mL.min-1.g-1
509,CHEMBL4546859,O=C(c1ccccc1)N1CCCC(c2cn3cccnc3n2)C1,338.50,mL.min-1.kg-1
510,CHEMBL4574040,O=C(c1ccccc1)N1CCCC(c2nc3ncccc3[nH]2)C1,172.78,mL.min-1.g-1
511,CHEMBL4574040,O=C(c1ccccc1)N1CCCC(c2nc3ncccc3[nH]2)C1,763.00,mL.min-1.kg-1
512,CHEMBL4436506,O=C(c1ccccn1)N1CCCC(c2cc3ncccc3[nH]2)C1,163.91,mL.min-1.g-1
513,CHEMBL4436506,O=C(c1ccccn1)N1CCCC(c2cc3ncccc3[nH]2)C1,523.33,mL.min-1.kg-1
514,CHEMBL1939219,O=C1CC(=O)CC([C@@H]2C[C@H]2c2cc(C(F)(F)F)cc(C(...,82.00,mL.min-1.kg-1
515,CHEMBL1939219,O=C1CC(=O)CC([C@@H]2C[C@H]2c2cc(C(F)(F)F)cc(C(...,63.00,mL.min-1.kg-1
516,CHEMBL4470549,O=C1c2ccccc2CN1CCc1cc2ncccc2[nH]1,212.98,mL.min-1.g-1
517,CHEMBL4470549,O=C1c2ccccc2CN1CCc1cc2ncccc2[nH]1,1086.33,mL.min-1.kg-1
518,CHEMBL4849813,O=S(=O)(Nc1cccc(F)n1)c1cc(F)c(OC2CCN(CC(F)(F)F...,50.00,mL.min-1.kg-1
519,CHEMBL4849813,O=S(=O)(Nc1cccc(F)n1)c1cc(F)c(OC2CCN(CC(F)(F)F...,45.00,mL.min-1.kg-1
520,CHEMBL4854735,O=S(=O)(Nc1cccc(F)n1)c1cc(F)c(O[C@H]2CCN(CC(F)...,65.00,mL.min-1.kg-1
521,CHEMBL4854735,O=S(=O)(Nc1cccc(F)n1)c1cc(F)c(O[C@H]2CCN(CC(F)...,63.00,mL.min-1.kg-1
522,CHEMBL4854735,O=S(=O)(Nc1cccc(F)n1)c1cc(F)c(O[C@H]2CCN(CC(F)...,74.00,mL.min-1.kg-1
523,CHEMBL2325478,O=c1cc(CNc2cc(Cl)cc(Cl)c2)[nH][nH]1,23.00,mL.min-1.kg-1
524,CHEMBL2325478,O=c1cc(CNc2cc(Cl)cc(Cl)c2)[nH][nH]1,78.00,mL.min-1.kg-1
525,CHEMBL1939222,O=c1cc(COc2cc(Cl)cc(Cl)c2)[nH][nH]1,21.00,mL.min-1.kg-1
526,CHEMBL1939222,O=c1cc(COc2cc(Cl)cc(Cl)c2)[nH][nH]1,64.00,mL.min-1.kg-1
527,CHEMBL3330226,O=c1nc(N2CCN(CC3CCCCC3)CC2)sc2c([N+](=O)[O-])c...,20.10,mL.min-1.g-1
528,CHEMBL3330226,O=c1nc(N2CCN(CC3CCCCC3)CC2)sc2c([N+](=O)[O-])c...,173.60,mL.min-1.kg-1
529,CHEMBL4575354,OC1(c2cc3ncccc3[nH]2)CCN(Cc2ccccc2)CC1,433.90,mL.min-1.g-1
530,CHEMBL4575354,OC1(c2cc3ncccc3[nH]2)CCN(Cc2ccccc2)CC1,1920.17,mL.min-1.kg-1
531,CHEMBL5070261,OC1Cc2cc(Cl)ccc2-n2c(nnc2[C@H]2CC[C@H](Oc3cccc...,6.30,mL.min-1.g-1
532,CHEMBL5070261,OC1Cc2cc(Cl)ccc2-n2c(nnc2[C@H]2CC[C@H](Oc3cccc...,6.00,mL.min-1.g-1
533,CHEMBL5070075,O[C@@H]1Cc2cc(Cl)ccc2-n2c(nnc2[C@H]2CC[C@H](Oc...,5.10,mL.min-1.g-1
534,CHEMBL5070075,O[C@@H]1Cc2cc(Cl)ccc2-n2c(nnc2[C@H]2CC[C@H](Oc...,5.00,mL.min-1.g-1
535,CHEMBL5074709,O[C@H]1Cc2cc(Cl)ccc2-n2c(nnc2[C@H]2CC[C@H](Oc3...,6.70,mL.min-1.g-1
536,CHEMBL5074709,O[C@H]1Cc2cc(Cl)ccc2-n2c(nnc2[C@H]2CC[C@H](Oc3...,7.00,mL.min-1.g-1
537,CHEMBL1828820,c1cc([C@H]2CC[C@]3(CC2)OO[C@]2(O3)C3CC4CC(C3)C...,14.00,mL.min-1.g-1
538,CHEMBL1828820,c1cc([C@H]2CC[C@]3(CC2)OO[C@]2(O3)C3CC4CC(C3)C...,14.00,mL.min-1.g-1
539,CHEMBL1861693,c1ccc(-c2ccc(-c3nc(CNC4CCCCCC4)co3)cc2)cc1,4.00,mL.min-1.g-1
540,CHEMBL1861693,c1ccc(-c2ccc(-c3nc(CNC4CCCCCC4)co3)cc2)cc1,10.00,mL.min-1.g-1
541,CHEMBL3088160,c1csc(-c2cc(CNC34CC5CC(CC(C5)C3)C4)no2)c1,5290.90,mL.min-1.kg-1
542,CHEMBL3088160,c1csc(-c2cc(CNC34CC5CC(CC(C5)C3)C4)no2)c1,5290.90,mL.min-1.kg-1
543,CHEMBL3088160,c1csc(-c2cc(CNC34CC5CC(CC(C5)C3)C4)no2)c1,5290.90,mL.min-1.kg-1